pipeline {
    agent any
    
    tools {
        nodejs 'Node16'
    }

    stages {
        stage("Clone") {
            steps {
                sh 'ls -R'
                git url:'https://github.com/apiwizlabs/wizdesk.git', branch: 'main'
                sh 'pwd'
                sh 'ls -R'
            }
        }

        stage('Build Frontend') {
            steps {
                sh 'pwd'
                sh 'npm install'
                sh 'npm run build'
                sh 'docker build . -t apiwiz-frontend'
            }
        }

        stage('Build Backend') {
            steps {
                sh 'cd Server && npm install'
                sh 'cd Server && docker build . -t apiwiz-backend'
            }
        }

        stage('Test') {
            steps {
                // Run the tests for the frontend
                sh 'npm test'

                // Run the tests for the backend
                sh 'cd Server && npm test'
            }
        }

    }
}
